#!/bin/bash

# # Define the file to be updated
# file="src/ui/MainWindow.py"

# # update MainWindow.py
# pyuic6 designer/mainwindow.ui -o $file

# # Define the file containing the list of object names
# object_names_file="src/widget_list_MainWindow.txt"

# # Check if the files exist
# if [[ ! -f "$file" ]]; then
#   echo "File $file not found!"
#   exit 1
# fi

# if [[ ! -f "$object_names_file" ]]; then
#   echo "File $object_names_file not found!"
#   exit 1
# fi

# # Add the import for CustomWidgets as cw if it doesn't exist
# if ! grep -q "import src.common.CustomWidgets as cw" "$file"; then
#   echo "Adding import for src.common.CustomWidgets as cw..."
#   sed -i '' "1i\\
# import src.common.CustomWidgets as cw
# " "$file"
# fi

# # Replace 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names
# echo "Replacing 'QtWidgets.QLineEdit' with 'cw.CustomLineEdit' for specified object names..."
# while IFS= read -r object_name; do
#   sed -i '' "s/${object_name} = QtWidgets.QLineEdit/${object_name} = cw.CustomLineEdit/g" "$file"
# done < "$object_names_file"

# # Replace 'import resources_rc' with 'import src.ui.resources_rc'
# echo "Replacing 'import resources_rc' with 'import src.ui.resources_rc'..."
# sed -i '' "s/import resources_rc/import src.ui.resources_rc/g" "$file"

# echo "Processing complete for $file"
# echo

# Windows without custom widgets that need to be replaced
names=("AnalyteSelectionDialog" "FieldSelectionDialog" "IsotopeSelectionDialog" "PlotViewer" "PreferencesWindow" "QuickViewDialog" "SpotImportDialog")

for name in "${names[@]}"; do
  file="src/ui/$name.py"

  # Generate the .py file from the .ui file using pyuic6
  pyuic6 -x designer/$name.ui -o $file

  echo "Processing completed for $name."
done

# Define the file to be updated
names=("MainWindow" "FileSelectorDialog" "MapImportDialog")

# Function to determine widget type from object name
get_widget_type() {
  local object_name=$1
  # Extract widget type from object name using pattern matching
  case "$object_name" in
    self.tableWidget*) echo "TableWidget" ;;
    self.lineEdit*) echo "LineEdit" ;;
    self.treeView*) echo "TreeView" ;;
    self.dockWidget*) echo "DockWidget" ;;
    # Add more patterns as needed
    *) echo "Unknown" ;;
  esac
}

# Iterate over each name in the list
for name in "${names[@]}"; do
  file="src/ui/$name.py"

  if [ "$name" = "mainwindow" ]; then
    # update MainWindow.py
    pyuic6 designer/mainwindow.ui -o $file
  else
    # Generate the .py file from the .ui file using pyuic6
    pyuic6 -x designer/$name.ui -o $file
  fi

  # Define the file containing the list of object names
  object_names_file="src/widget_list_$name.txt"

  # Check if the generated .py file exists
  if [[ ! -f "$file" ]]; then
    echo "File $file not found for $name!"
    continue
  fi

  # Check if the object names file exists
  if [[ ! -f "$object_names_file" ]]; then
    echo "File $object_names_file not found for $name!"
    continue
  fi

  # Add the import for CustomWidgets as cw if it doesn't exist
  if ! grep -q "import src.common.CustomWidgets as cw" "$file"; then
    echo "Adding import for src.common.CustomWidgets as cw to $file..."
    sed -i '' "1i\\
import src.common.CustomWidgets as cw
" "$file"
  fi

  # Replace widget types based on the object names
  echo "Replacing 'QtWidgets.QWidgetType' with 'cw.CustomWidgetType' for specified object names in $file..."

  while IFS= read -r object_name; do
    widget_type=$(get_widget_type "$object_name")
    echo "    object name: $object_name, widget type: $widget_type"
    sed -i '' "s/${object_name} = QtWidgets.Q${widget_type}/${object_name} = cw.Custom${widget_type}/g" "$file"
  done < "$object_names_file"

  if [ "$name" = "mainwindow" ]; then
    # Replace 'import resources_rc' with 'import src.ui.resources_rc'
    echo "Replacing 'import resources_rc' with 'import src.ui.resources_rc'..."
    sed -i '' "s/import resources_rc/import src.ui.resources_rc/g" "$file"
  fi

  echo "Processing completed for $name."
  echo

done

# update blockly for workflow
cd blockly
npx webpack --config webpack.config.js