# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/ExcelConcatenator.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(752, 441)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(80, 370, 471, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.tableWidgetMetaData = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetMetaData.setGeometry(QtCore.QRect(10, 40, 711, 291))
        self.tableWidgetMetaData.setObjectName("tableWidgetMetaData")
        self.tableWidgetMetaData.setColumnCount(8)
        self.tableWidgetMetaData.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMetaData.setHorizontalHeaderItem(7, item)
        self.pushButtonLoadSelection = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoadSelection.setGeometry(QtCore.QRect(30, 370, 111, 31))
        self.pushButtonLoadSelection.setObjectName("pushButtonLoadSelection")
        self.pushButtonSaveSelection = QtWidgets.QPushButton(Dialog)
        self.pushButtonSaveSelection.setGeometry(QtCore.QRect(150, 370, 100, 32))
        self.pushButtonSaveSelection.setObjectName("pushButtonSaveSelection")
        self.pushButtonImport = QtWidgets.QPushButton(Dialog)
        self.pushButtonImport.setGeometry(QtCore.QRect(270, 370, 111, 31))
        self.pushButtonImport.setObjectName("pushButtonImport")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Sample ID"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "type"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "File Direction"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Scan Direction"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Delimiter"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Scan number pos"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Spot Size"))
        item = self.tableWidgetMetaData.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "Intraline Distance"))
        self.pushButtonLoadSelection.setText(_translate("Dialog", "Open Directory"))
        self.pushButtonSaveSelection.setText(_translate("Dialog", "Save MetaData"))
        self.pushButtonImport.setText(_translate("Dialog", "import"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
