import src.CustomWidgets as cw
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/FileSelectorDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileSelectorDialog(object):
    def setupUi(self, FileSelectorDialog):
        FileSelectorDialog.setObjectName("FileSelectorDialog")
        FileSelectorDialog.resize(762, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileSelectorDialog.sizePolicy().hasHeightForWidth())
        FileSelectorDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileSelectorDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDialog = QtWidgets.QLabel(FileSelectorDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.labelDialog.setFont(font)
        self.labelDialog.setObjectName("labelDialog")
        self.verticalLayout.addWidget(self.labelDialog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelDirectory = QtWidgets.QLabel(FileSelectorDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDirectory.setFont(font)
        self.labelDirectory.setObjectName("labelDirectory")
        self.horizontalLayout.addWidget(self.labelDirectory)
        self.lineEditDirectory = QtWidgets.QLineEdit(FileSelectorDialog)
        self.lineEditDirectory.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDirectory.setFont(font)
        self.lineEditDirectory.setObjectName("lineEditDirectory")
        self.horizontalLayout.addWidget(self.lineEditDirectory)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetFileMetadata = cw.CustomTableWidget(FileSelectorDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidgetFileMetadata.setFont(font)
        self.tableWidgetFileMetadata.setObjectName("tableWidgetFileMetadata")
        self.tableWidgetFileMetadata.setColumnCount(6)
        self.tableWidgetFileMetadata.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFileMetadata.setHorizontalHeaderItem(5, item)
        self.verticalLayout.addWidget(self.tableWidgetFileMetadata)
        self.buttonBox = QtWidgets.QDialogButtonBox(FileSelectorDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FileSelectorDialog)
        self.buttonBox.accepted.connect(FileSelectorDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FileSelectorDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileSelectorDialog)

    def retranslateUi(self, FileSelectorDialog):
        _translate = QtCore.QCoreApplication.translate
        FileSelectorDialog.setWindowTitle(_translate("FileSelectorDialog", "Dialog"))
        self.labelDialog.setText(_translate("FileSelectorDialog", "Verify field import parameters"))
        self.labelDirectory.setText(_translate("FileSelectorDialog", "Directory:"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(0)
        item.setText(_translate("FileSelectorDialog", "Import"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(1)
        item.setText(_translate("FileSelectorDialog", "Filename"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(2)
        item.setText(_translate("FileSelectorDialog", "Field Type"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(3)
        item.setText(_translate("FileSelectorDialog", "Analyte 1"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(4)
        item.setText(_translate("FileSelectorDialog", "Analyte 2"))
        item = self.tableWidgetFileMetadata.horizontalHeaderItem(5)
        item.setText(_translate("FileSelectorDialog", "Units"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FileSelectorDialog = QtWidgets.QDialog()
    ui = Ui_FileSelectorDialog()
    ui.setupUi(FileSelectorDialog)
    FileSelectorDialog.show()
    sys.exit(app.exec_())
