# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/IsotopeSelectionDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(517, 358)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonCancel = QtWidgets.QPushButton(Dialog)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.gridLayout.addWidget(self.pushButtonCancel, 5, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.pushButtonLoadSelection = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoadSelection.setObjectName("pushButtonLoadSelection")
        self.gridLayout.addWidget(self.pushButtonLoadSelection, 5, 1, 1, 1)
        self.tableWidgetIsotopes = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetIsotopes.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.tableWidgetIsotopes.setObjectName("tableWidgetIsotopes")
        self.tableWidgetIsotopes.setColumnCount(0)
        self.tableWidgetIsotopes.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetIsotopes, 1, 1, 3, 4)
        self.pushButtonSaveSelection = QtWidgets.QPushButton(Dialog)
        self.pushButtonSaveSelection.setObjectName("pushButtonSaveSelection")
        self.gridLayout.addWidget(self.pushButtonSaveSelection, 5, 2, 1, 1)
        self.pushButtonDone = QtWidgets.QPushButton(Dialog)
        self.pushButtonDone.setObjectName("pushButtonDone")
        self.gridLayout.addWidget(self.pushButtonDone, 5, 6, 1, 1)
        self.labelColorbar = QtWidgets.QLabel(Dialog)
        self.labelColorbar.setMaximumSize(QtCore.QSize(40, 200))
        self.labelColorbar.setText("")
        self.labelColorbar.setObjectName("labelColorbar")
        self.gridLayout.addWidget(self.labelColorbar, 2, 5, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 6, 1, 1)
        self.comboBoxCorrelation = QtWidgets.QComboBox(Dialog)
        self.comboBoxCorrelation.setObjectName("comboBoxCorrelation")
        self.gridLayout.addWidget(self.comboBoxCorrelation, 0, 2, 1, 1)
        self.comboBoxScale = QtWidgets.QComboBox(Dialog)
        self.comboBoxScale.setObjectName("comboBoxScale")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.comboBoxScale.addItem("")
        self.gridLayout.addWidget(self.comboBoxScale, 1, 6, 1, 1)
        self.tableWidgetSelected = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetSelected.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tableWidgetSelected.setObjectName("tableWidgetSelected")
        self.tableWidgetSelected.setColumnCount(0)
        self.tableWidgetSelected.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidgetSelected, 2, 6, 2, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Select Isotopes"))
        self.pushButtonCancel.setText(_translate("Dialog", "Cancel"))
        self.label_2.setText(_translate("Dialog", "Correlation Type"))
        self.pushButtonLoadSelection.setText(_translate("Dialog", "Load Selection"))
        self.pushButtonSaveSelection.setText(_translate("Dialog", "Save Selection"))
        self.pushButtonDone.setText(_translate("Dialog", "Done"))
        self.label.setText(_translate("Dialog", "Selected list"))
        self.comboBoxScale.setToolTip(_translate("Dialog", "Apply scale to all samples"))
        self.comboBoxScale.setItemText(0, _translate("Dialog", "linear"))
        self.comboBoxScale.setItemText(1, _translate("Dialog", "log"))
        self.comboBoxScale.setItemText(2, _translate("Dialog", "mixed"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
