# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/QuickViewDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuickViewDialog(object):
    def setupUi(self, QuickViewDialog):
        QuickViewDialog.setObjectName("QuickViewDialog")
        QuickViewDialog.resize(256, 640)
        self.verticalLayout = QtWidgets.QVBoxLayout(QuickViewDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableWidget = QtWidgets.QTableWidget(QuickViewDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(QuickViewDialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditViewName = QtWidgets.QLineEdit(QuickViewDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditViewName.setFont(font)
        self.lineEditViewName.setText("")
        self.lineEditViewName.setObjectName("lineEditViewName")
        self.horizontalLayout.addWidget(self.lineEditViewName)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.toolButtonSort = QtWidgets.QToolButton(QuickViewDialog)
        self.toolButtonSort.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonSort.setMaximumSize(QtCore.QSize(32, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/icons/icon-sort-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSort.setIcon(icon)
        self.toolButtonSort.setIconSize(QtCore.QSize(28, 28))
        self.toolButtonSort.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButtonSort.setObjectName("toolButtonSort")
        self.horizontalLayout_3.addWidget(self.toolButtonSort)
        self.toolButtonSave = QtWidgets.QToolButton(QuickViewDialog)
        self.toolButtonSave.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonSave.setMaximumSize(QtCore.QSize(32, 32))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/icons/icon-save-file-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonSave.setIcon(icon1)
        self.toolButtonSave.setIconSize(QtCore.QSize(28, 28))
        self.toolButtonSave.setObjectName("toolButtonSave")
        self.horizontalLayout_3.addWidget(self.toolButtonSave)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButtonClose = QtWidgets.QPushButton(QuickViewDialog)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.horizontalLayout_3.addWidget(self.pushButtonClose)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(QuickViewDialog)
        QtCore.QMetaObject.connectSlotsByName(QuickViewDialog)

    def retranslateUi(self, QuickViewDialog):
        _translate = QtCore.QCoreApplication.translate
        QuickViewDialog.setWindowTitle(_translate("QuickViewDialog", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("QuickViewDialog", "New Column"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("QuickViewDialog", "Show"))
        self.label.setText(_translate("QuickViewDialog", "Enter name:"))
        self.toolButtonSort.setText(_translate("QuickViewDialog", "..."))
        self.toolButtonSave.setText(_translate("QuickViewDialog", "..."))
        self.pushButtonClose.setText(_translate("QuickViewDialog", "Close"))
import src.ui.resources_rc
