
from PyQt5.QtCore import Qt, QSize
from PyQt5.QtGui import QStandardItem, QStandardItemModel, QIcon, QFont, QIntValidator
from PyQt5.QtWidgets import ( 
        QMessageBox, QInputDialog, QWidget, QTableWidgetItem, QVBoxLayout, QHBoxLayout, QGroupBox,
        QToolButton, QComboBox, QSpinBox, QSizePolicy, QFormLayout, QListView, QToolBar,
        QAction, QLabel, QHeaderView, QTableWidget, QScrollArea, QMainWindow, QWidgetAction
    )
from src.common.CustomWidgets import CustomDockWidget, CustomLineEdit, CustomComboBox, ToggleSwitch
from src.app.UIControl import UIFieldLogic
from pyqtgraph import ( ScatterPlotItem )
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.colors as colors
from matplotlib.collections import PathCollection
import numpy as np

# Mask object
# -------------------------------
class MaskObj:
    def __init__(self, initial_value=None):
        self._value = initial_value
        self._callbacks = []

    @property
    def value(self):
        return self._value

    @value.setter
    def value(self, new_value):
        old_value = self._value
        self._value = new_value 
        self._notify_observers(old_value, new_value)

    def _notify_observers(self, old_value, new_value):
        for callback in self._callbacks:
            callback(old_value, new_value)
    
    def register_callback(self, callback):
        self._callbacks.append(callback)


# remove lines from approx 1980 to 2609 in MainWindow.py (Masking Toolbox dockWidgetMaskToolbox) when complete

class MaskDock(CustomDockWidget, UIFieldLogic):
    def __init__(self, parent=None):
        if not isinstance(parent, QMainWindow):
            raise TypeError("Parent must be an instance of QMainWindow.")

        super().__init__(parent)
        self.main_window = parent

        self.dockWidgetMaskToolbox = cw.CustomDockWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetMaskToolbox.sizePolicy().hasHeightForWidth())
        self.dockWidgetMaskToolbox.setSizePolicy(sizePolicy)
        self.dockWidgetMaskToolbox.setMinimumSize(QtCore.QSize(855, 367))
        self.dockWidgetMaskToolbox.setMaximumSize(QtCore.QSize(524287, 524287))
        self.dockWidgetMaskToolbox.setFloating(False)
        self.dockWidgetMaskToolbox.setFeatures(QtWidgets.QDockWidget.DockWidgetFloatable)
        self.dockWidgetMaskToolbox.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea)
        self.dockWidgetMaskToolbox.setObjectName("dockWidgetMaskToolbox")
        self.dockWidgetContentsBottomTabs = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContentsBottomTabs.sizePolicy().hasHeightForWidth())
        self.dockWidgetContentsBottomTabs.setSizePolicy(sizePolicy)
        self.dockWidgetContentsBottomTabs.setObjectName("dockWidgetContentsBottomTabs")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.dockWidgetContentsBottomTabs)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.tabWidgetMask = QtWidgets.QTabWidget(self.dockWidgetContentsBottomTabs)
        self.tabWidgetMask.setEnabled(True)
        self.tabWidgetMask.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidgetMask.setMaximumSize(QtCore.QSize(524287, 524287))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.tabWidgetMask.setFont(font)
        self.tabWidgetMask.setToolTip("")
        self.tabWidgetMask.setObjectName("tabWidgetMask")

        self.tabWidgetMask.addTab(self.PolygonTab, icon32, "")

        self.ClusterTab = QtWidgets.QWidget()
        self.ClusterTab.setObjectName("ClusterTab")

        self.dockWidgetMaskToolbox.setWidget(self.dockWidgetContentsBottomTabs)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidgetMaskToolbox)

class FilterTab():
    def __init__(self, parent=None):
        self.tabFilterList = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabFilterList.sizePolicy().hasHeightForWidth())
        self.tabFilterList.setSizePolicy(sizePolicy)
        self.tabFilterList.setObjectName("tabFilterList")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.tabFilterList)
        self.verticalLayout_12.setContentsMargins(12, -1, 12, 12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayoutFilter = QtWidgets.QHBoxLayout()
        self.horizontalLayoutFilter.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayoutFilter.setSpacing(1)
        self.horizontalLayoutFilter.setObjectName("horizontalLayoutFilter")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tabFilterList)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 527, 292))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_72 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.groupBoxFilter = QtWidgets.QGroupBox(self.scrollAreaWidgetContents_4)
        self.groupBoxFilter.setTitle("")
        self.groupBoxFilter.setObjectName("groupBoxFilter")
        self.formLayout_8 = QtWidgets.QFormLayout(self.groupBoxFilter)
        self.formLayout_8.setContentsMargins(3, 0, 3, 0)
        self.formLayout_8.setObjectName("formLayout_8")
        self.labelFilterPresets = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFilterPresets.setObjectName("labelFilterPresets")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.labelFilterPresets)
        self.comboBoxFilterPresets = QtWidgets.QComboBox(self.groupBoxFilter)
        self.comboBoxFilterPresets.setObjectName("comboBoxFilterPresets")
        self.formLayout_8.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBoxFilterPresets)
        self.comboBoxFilterFieldType = QtWidgets.QComboBox(self.groupBoxFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFilterFieldType.sizePolicy().hasHeightForWidth())
        self.comboBoxFilterFieldType.setSizePolicy(sizePolicy)
        self.comboBoxFilterFieldType.setObjectName("comboBoxFilterFieldType")
        self.comboBoxFilterFieldType.addItem("")
        self.comboBoxFilterFieldType.addItem("")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.comboBoxFilterFieldType)
        self.comboBoxFilterField = QtWidgets.QComboBox(self.groupBoxFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxFilterField.sizePolicy().hasHeightForWidth())
        self.comboBoxFilterField.setSizePolicy(sizePolicy)
        self.comboBoxFilterField.setObjectName("comboBoxFilterField")
        self.formLayout_8.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxFilterField)
        self.labelFMinVal = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFMinVal.setObjectName("labelFMinVal")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.labelFMinVal)
        self.lineEditFMin = cw.CustomLineEdit(self.groupBoxFilter)
        self.lineEditFMin.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditFMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditFMin.setObjectName("lineEditFMin")
        self.formLayout_8.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditFMin)
        self.labelFMinQ = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFMinQ.setObjectName("labelFMinQ")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.labelFMinQ)
        self.doubleSpinBoxFMinQ = QtWidgets.QDoubleSpinBox(self.groupBoxFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFMinQ.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFMinQ.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFMinQ.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.doubleSpinBoxFMinQ.setFont(font)
        self.doubleSpinBoxFMinQ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxFMinQ.setKeyboardTracking(False)
        self.doubleSpinBoxFMinQ.setObjectName("doubleSpinBoxFMinQ")
        self.formLayout_8.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxFMinQ)
        self.labelFMaxVal = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFMaxVal.setObjectName("labelFMaxVal")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.labelFMaxVal)
        self.lineEditFMax = cw.CustomLineEdit(self.groupBoxFilter)
        self.lineEditFMax.setMinimumSize(QtCore.QSize(0, 0))
        self.lineEditFMax.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditFMax.setObjectName("lineEditFMax")
        self.formLayout_8.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditFMax)
        self.labelFMaxQ = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFMaxQ.setObjectName("labelFMaxQ")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.labelFMaxQ)
        self.doubleSpinBoxFMaxQ = QtWidgets.QDoubleSpinBox(self.groupBoxFilter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxFMaxQ.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxFMaxQ.setSizePolicy(sizePolicy)
        self.doubleSpinBoxFMaxQ.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.doubleSpinBoxFMaxQ.setFont(font)
        self.doubleSpinBoxFMaxQ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBoxFMaxQ.setKeyboardTracking(False)
        self.doubleSpinBoxFMaxQ.setObjectName("doubleSpinBoxFMaxQ")
        self.formLayout_8.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.doubleSpinBoxFMaxQ)
        self.labelFilterOperator = QtWidgets.QLabel(self.groupBoxFilter)
        self.labelFilterOperator.setObjectName("labelFilterOperator")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.labelFilterOperator)
        self.comboBoxFilterOperator = QtWidgets.QComboBox(self.groupBoxFilter)
        self.comboBoxFilterOperator.setObjectName("comboBoxFilterOperator")
        self.comboBoxFilterOperator.addItem("")
        self.comboBoxFilterOperator.addItem("")
        self.formLayout_8.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.comboBoxFilterOperator)
        self.checkBoxPersistentFilter = QtWidgets.QCheckBox(self.groupBoxFilter)
        self.checkBoxPersistentFilter.setObjectName("checkBoxPersistentFilter")
        self.formLayout_8.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.checkBoxPersistentFilter)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem13)
        self.toolButtonAddFilter = QtWidgets.QToolButton(self.groupBoxFilter)
        self.toolButtonAddFilter.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonAddFilter.setMaximumSize(QtCore.QSize(28, 28))
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(":/resources/icons/icon-filter-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonAddFilter.setIcon(icon29)
        self.toolButtonAddFilter.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonAddFilter.setObjectName("toolButtonAddFilter")
        self.horizontalLayout_43.addWidget(self.toolButtonAddFilter)
        self.formLayout_8.setLayout(7, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_43)
        self.verticalLayout_72.addWidget(self.groupBoxFilter)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_4)
        self.horizontalLayoutFilter.addWidget(self.scrollArea_2)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(12, -1, 12, -1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tableWidgetFilters = QtWidgets.QTableWidget(self.tabFilterList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetFilters.sizePolicy().hasHeightForWidth())
        self.tableWidgetFilters.setSizePolicy(sizePolicy)
        self.tableWidgetFilters.setMinimumSize(QtCore.QSize(400, 0))
        self.tableWidgetFilters.setMaximumSize(QtCore.QSize(524287, 524287))
        self.tableWidgetFilters.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetFilters.setObjectName("tableWidgetFilters")
        self.tableWidgetFilters.setColumnCount(8)
        self.tableWidgetFilters.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetFilters.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFilters.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetFilters.setHorizontalHeaderItem(7, item)
        self.tableWidgetFilters.horizontalHeader().setDefaultSectionSize(80)
        self.tableWidgetFilters.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_9.addWidget(self.tableWidgetFilters)
        self.labelFilterInfo = QtWidgets.QLabel(self.tabFilterList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelFilterInfo.sizePolicy().hasHeightForWidth())
        self.labelFilterInfo.setSizePolicy(sizePolicy)
        self.labelFilterInfo.setMinimumSize(QtCore.QSize(0, 18))
        self.labelFilterInfo.setMaximumSize(QtCore.QSize(524287, 18))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.labelFilterInfo.setFont(font)
        self.labelFilterInfo.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFilterInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.labelFilterInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelFilterInfo.setWordWrap(True)
        self.labelFilterInfo.setObjectName("labelFilterInfo")
        self.verticalLayout_9.addWidget(self.labelFilterInfo)
        self.horizontalLayoutFilter.addLayout(self.verticalLayout_9)
        self.verticalLayout_71 = QtWidgets.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.groupBoxFilterTableControl = QtWidgets.QGroupBox(self.tabFilterList)
        self.groupBoxFilterTableControl.setMinimumSize(QtCore.QSize(40, 0))
        self.groupBoxFilterTableControl.setMaximumSize(QtCore.QSize(40, 16777215))
        self.groupBoxFilterTableControl.setTitle("")
        self.groupBoxFilterTableControl.setObjectName("groupBoxFilterTableControl")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBoxFilterTableControl)
        self.verticalLayout_2.setContentsMargins(3, 6, 3, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolButtonFilterSelectAll = QtWidgets.QToolButton(self.groupBoxFilterTableControl)
        self.toolButtonFilterSelectAll.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterSelectAll.setMaximumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterSelectAll.setIcon(icon21)
        self.toolButtonFilterSelectAll.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonFilterSelectAll.setObjectName("toolButtonFilterSelectAll")
        self.verticalLayout_2.addWidget(self.toolButtonFilterSelectAll)
        self.toolButtonFilterUp = QtWidgets.QToolButton(self.groupBoxFilterTableControl)
        self.toolButtonFilterUp.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterUp.setMaximumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterUp.setIcon(icon22)
        self.toolButtonFilterUp.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonFilterUp.setObjectName("toolButtonFilterUp")
        self.verticalLayout_2.addWidget(self.toolButtonFilterUp)
        self.toolButtonFilterDown = QtWidgets.QToolButton(self.groupBoxFilterTableControl)
        self.toolButtonFilterDown.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterDown.setMaximumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterDown.setIcon(icon23)
        self.toolButtonFilterDown.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonFilterDown.setObjectName("toolButtonFilterDown")
        self.verticalLayout_2.addWidget(self.toolButtonFilterDown)
        self.toolButtonFilterSave = QtWidgets.QToolButton(self.groupBoxFilterTableControl)
        self.toolButtonFilterSave.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterSave.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonFilterSave.setFont(font)
        self.toolButtonFilterSave.setIcon(icon4)
        self.toolButtonFilterSave.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonFilterSave.setObjectName("toolButtonFilterSave")
        self.verticalLayout_2.addWidget(self.toolButtonFilterSave)
        self.toolButtonFilterRemove = QtWidgets.QToolButton(self.groupBoxFilterTableControl)
        self.toolButtonFilterRemove.setEnabled(True)
        self.toolButtonFilterRemove.setMinimumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterRemove.setMaximumSize(QtCore.QSize(28, 28))
        self.toolButtonFilterRemove.setIcon(icon5)
        self.toolButtonFilterRemove.setIconSize(QtCore.QSize(20, 20))
        self.toolButtonFilterRemove.setObjectName("toolButtonFilterRemove")
        self.verticalLayout_2.addWidget(self.toolButtonFilterRemove)
        self.verticalLayout_71.addWidget(self.groupBoxFilterTableControl)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_71.addItem(spacerItem14)
        self.horizontalLayoutFilter.addLayout(self.verticalLayout_71)
        self.verticalLayout_12.addLayout(self.horizontalLayoutFilter)
        self.tabWidgetMask.addTab(self.tabFilterList, icon29, "")
        self.PolygonTab = QtWidgets.QWidget()
        self.PolygonTab.setObjectName("PolygonTab")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout(self.PolygonTab)
        self.horizontalLayout_52.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.scrollAreaFilter = QtWidgets.QScrollArea(self.PolygonTab)
        self.scrollAreaFilter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaFilter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollAreaFilter.setWidgetResizable(True)
        self.scrollAreaFilter.setObjectName("scrollAreaFilter")
        self.scrollAreaWidgetContentsFilter = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsFilter.setGeometry(QtCore.QRect(0, 0, 1114, 284))
        self.scrollAreaWidgetContentsFilter.setObjectName("scrollAreaWidgetContentsFilter")
        self.verticalLayout_49 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsFilter)
        self.verticalLayout_49.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContentsFilter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_10.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        pass

class PolygonTab():
    def __init__(self, parent=None):
        self.toolButtonEdgeDetect = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButtonEdgeDetect.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonEdgeDetect.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonEdgeDetect.setFont(font)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(":/resources/icons/icon-spotlight-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonEdgeDetect.setIcon(icon30)
        self.toolButtonEdgeDetect.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonEdgeDetect.setCheckable(True)
        self.toolButtonEdgeDetect.setObjectName("toolButtonEdgeDetect")
        self.horizontalLayout_10.addWidget(self.toolButtonEdgeDetect)
        self.comboBoxEdgeDetectMethod = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBoxEdgeDetectMethod.setObjectName("comboBoxEdgeDetectMethod")
        self.comboBoxEdgeDetectMethod.addItem("")
        self.comboBoxEdgeDetectMethod.addItem("")
        self.comboBoxEdgeDetectMethod.addItem("")
        self.horizontalLayout_10.addWidget(self.comboBoxEdgeDetectMethod)
        spacerItem15 = QtWidgets.QSpacerItem(114, 33, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem15)
        self.verticalLayout_49.addWidget(self.groupBox_2)
        self.groupBoxPolygon = QtWidgets.QGroupBox(self.scrollAreaWidgetContentsFilter)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.groupBoxPolygon.setFont(font)
        self.groupBoxPolygon.setObjectName("groupBoxPolygon")
        self.verticalLayout_50 = QtWidgets.QVBoxLayout(self.groupBoxPolygon)
        self.verticalLayout_50.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.toolButtonPolyLoad = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyLoad.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyLoad.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyLoad.setFont(font)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(":/resources/icons/icon-open-file-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyLoad.setIcon(icon31)
        self.toolButtonPolyLoad.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyLoad.setObjectName("toolButtonPolyLoad")
        self.horizontalLayout_9.addWidget(self.toolButtonPolyLoad)
        spacerItem16 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem16)
        self.toolButtonPolyCreate = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyCreate.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyCreate.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyCreate.setFont(font)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(":/resources/icons/icon-polygon-new-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyCreate.setIcon(icon32)
        self.toolButtonPolyCreate.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyCreate.setCheckable(True)
        self.toolButtonPolyCreate.setObjectName("toolButtonPolyCreate")
        self.horizontalLayout_9.addWidget(self.toolButtonPolyCreate)
        self.toolButtonPolyMovePoint = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyMovePoint.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyMovePoint.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyMovePoint.setFont(font)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(":/resources/icons/icon-move-point-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyMovePoint.setIcon(icon33)
        self.toolButtonPolyMovePoint.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyMovePoint.setCheckable(True)
        self.toolButtonPolyMovePoint.setObjectName("toolButtonPolyMovePoint")
        self.horizontalLayout_9.addWidget(self.toolButtonPolyMovePoint)
        self.toolButtonPolyAddPoint = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyAddPoint.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyAddPoint.setFont(font)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(":/resources/icons/icon-add-point-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyAddPoint.setIcon(icon34)
        self.toolButtonPolyAddPoint.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyAddPoint.setCheckable(True)
        self.toolButtonPolyAddPoint.setObjectName("toolButtonPolyAddPoint")
        self.horizontalLayout_9.addWidget(self.toolButtonPolyAddPoint)
        self.toolButtonPolyRemovePoint = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyRemovePoint.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyRemovePoint.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyRemovePoint.setFont(font)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(":/resources/icons/icon-remove-point-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyRemovePoint.setIcon(icon35)
        self.toolButtonPolyRemovePoint.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyRemovePoint.setCheckable(True)
        self.toolButtonPolyRemovePoint.setObjectName("toolButtonPolyRemovePoint")
        self.horizontalLayout_9.addWidget(self.toolButtonPolyRemovePoint)
        self.verticalLayout_50.addLayout(self.horizontalLayout_9)
        self.tableWidgetPolyPoints = QtWidgets.QTableWidget(self.groupBoxPolygon)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetPolyPoints.sizePolicy().hasHeightForWidth())
        self.tableWidgetPolyPoints.setSizePolicy(sizePolicy)
        self.tableWidgetPolyPoints.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetPolyPoints.setObjectName("tableWidgetPolyPoints")
        self.tableWidgetPolyPoints.setColumnCount(5)
        self.tableWidgetPolyPoints.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetPolyPoints.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPolyPoints.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetPolyPoints.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetPolyPoints.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetPolyPoints.setHorizontalHeaderItem(4, item)
        self.tableWidgetPolyPoints.horizontalHeader().setDefaultSectionSize(53)
        self.tableWidgetPolyPoints.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_50.addWidget(self.tableWidgetPolyPoints)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toolButtonPolyLink = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyLink.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyLink.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyLink.setFont(font)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(":/resources/icons/icon-link-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyLink.setIcon(icon36)
        self.toolButtonPolyLink.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyLink.setObjectName("toolButtonPolyLink")
        self.horizontalLayout_4.addWidget(self.toolButtonPolyLink)
        self.toolButtonPolyDelink = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyDelink.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyDelink.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyDelink.setFont(font)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(":/resources/icons/icon-unlink-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonPolyDelink.setIcon(icon37)
        self.toolButtonPolyDelink.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyDelink.setObjectName("toolButtonPolyDelink")
        self.horizontalLayout_4.addWidget(self.toolButtonPolyDelink)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem17)
        self.toolButtonPolySave = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolySave.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolySave.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolySave.setFont(font)
        self.toolButtonPolySave.setIcon(icon4)
        self.toolButtonPolySave.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolySave.setObjectName("toolButtonPolySave")
        self.horizontalLayout_4.addWidget(self.toolButtonPolySave)
        self.toolButtonPolyDelete = QtWidgets.QToolButton(self.groupBoxPolygon)
        self.toolButtonPolyDelete.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonPolyDelete.setMaximumSize(QtCore.QSize(32, 32))
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        font.setPointSize(11)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.toolButtonPolyDelete.setFont(font)
        self.toolButtonPolyDelete.setIcon(icon5)
        self.toolButtonPolyDelete.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonPolyDelete.setObjectName("toolButtonPolyDelete")
        self.horizontalLayout_4.addWidget(self.toolButtonPolyDelete)
        self.verticalLayout_50.addLayout(self.horizontalLayout_4)
        self.verticalLayout_49.addWidget(self.groupBoxPolygon)
        self.scrollAreaFilter.setWidget(self.scrollAreaWidgetContentsFilter)
        self.verticalLayout_8.addWidget(self.scrollAreaFilter)
        self.horizontalLayout_52.addLayout(self.verticalLayout_8)

        pass

class ClusterTab():
    def __init__(self, parent=None):
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout(self.ClusterTab)
        self.horizontalLayout_51.setContentsMargins(6, 6, 6, 6)
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.scrollAreaClusters = QtWidgets.QScrollArea(self.ClusterTab)
        self.scrollAreaClusters.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollAreaClusters.setFrameShadow(QtWidgets.QFrame.Plain)
        self.scrollAreaClusters.setWidgetResizable(True)
        self.scrollAreaClusters.setObjectName("scrollAreaClusters")
        self.scrollAreaWidgetContentsClusters = QtWidgets.QWidget()
        self.scrollAreaWidgetContentsClusters.setGeometry(QtCore.QRect(0, 0, 1114, 284))
        self.scrollAreaWidgetContentsClusters.setObjectName("scrollAreaWidgetContentsClusters")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContentsClusters)
        self.verticalLayout_40.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.horizontalLayout_35 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_35.setObjectName("horizontalLayout_35")
        self.labelClusterGroup = QtWidgets.QLabel(self.scrollAreaWidgetContentsClusters)
        self.labelClusterGroup.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelClusterGroup.setObjectName("labelClusterGroup")
        self.horizontalLayout_35.addWidget(self.labelClusterGroup)
        self.spinBoxClusterGroup = QtWidgets.QSpinBox(self.scrollAreaWidgetContentsClusters)
        self.spinBoxClusterGroup.setObjectName("spinBoxClusterGroup")
        self.horizontalLayout_35.addWidget(self.spinBoxClusterGroup)
        self.toolButtonClusterColor = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonClusterColor.setMaximumSize(QtCore.QSize(18, 18))
        self.toolButtonClusterColor.setText("")
        self.toolButtonClusterColor.setObjectName("toolButtonClusterColor")
        self.horizontalLayout_35.addWidget(self.toolButtonClusterColor)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem18)
        self.toolButtonClusterColorReset = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonClusterColorReset.setMinimumSize(QtCore.QSize(20, 20))
        self.toolButtonClusterColorReset.setMaximumSize(QtCore.QSize(20, 20))
        self.toolButtonClusterColorReset.setIcon(icon11)
        self.toolButtonClusterColorReset.setIconSize(QtCore.QSize(14, 14))
        self.toolButtonClusterColorReset.setObjectName("toolButtonClusterColorReset")
        self.horizontalLayout_35.addWidget(self.toolButtonClusterColorReset)
        self.verticalLayout_40.addLayout(self.horizontalLayout_35)
        self.tableWidgetViewGroups = QtWidgets.QTableWidget(self.scrollAreaWidgetContentsClusters)
        self.tableWidgetViewGroups.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidgetViewGroups.setObjectName("tableWidgetViewGroups")
        self.tableWidgetViewGroups.setColumnCount(3)
        self.tableWidgetViewGroups.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.tableWidgetViewGroups.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewGroups.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetViewGroups.setHorizontalHeaderItem(2, item)
        self.tableWidgetViewGroups.horizontalHeader().setDefaultSectionSize(53)
        self.verticalLayout_40.addWidget(self.tableWidgetViewGroups)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.toolButtonClusterLink = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonClusterLink.setEnabled(False)
        self.toolButtonClusterLink.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonClusterLink.setMaximumSize(QtCore.QSize(32, 32))
        self.toolButtonClusterLink.setIcon(icon36)
        self.toolButtonClusterLink.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonClusterLink.setObjectName("toolButtonClusterLink")
        self.horizontalLayout_50.addWidget(self.toolButtonClusterLink)
        self.toolButtonClusterDelink = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonClusterDelink.setEnabled(False)
        self.toolButtonClusterDelink.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonClusterDelink.setMaximumSize(QtCore.QSize(32, 32))
        self.toolButtonClusterDelink.setIcon(icon37)
        self.toolButtonClusterDelink.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonClusterDelink.setObjectName("toolButtonClusterDelink")
        self.horizontalLayout_50.addWidget(self.toolButtonClusterDelink)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem19)
        self.toolButtonGroupMask = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonGroupMask.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonGroupMask.setMaximumSize(QtCore.QSize(32, 32))
        icon38 = QtGui.QIcon()
        icon38.addPixmap(QtGui.QPixmap(":/resources/icons/icon-mask-dark-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupMask.setIcon(icon38)
        self.toolButtonGroupMask.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonGroupMask.setCheckable(True)
        self.toolButtonGroupMask.setObjectName("toolButtonGroupMask")
        self.horizontalLayout_50.addWidget(self.toolButtonGroupMask)
        self.toolButtonGroupMaskInverse = QtWidgets.QToolButton(self.scrollAreaWidgetContentsClusters)
        self.toolButtonGroupMaskInverse.setMinimumSize(QtCore.QSize(32, 32))
        self.toolButtonGroupMaskInverse.setMaximumSize(QtCore.QSize(32, 32))
        icon39 = QtGui.QIcon()
        icon39.addPixmap(QtGui.QPixmap(":/resources/icons/icon-mask-light-64.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButtonGroupMaskInverse.setIcon(icon39)
        self.toolButtonGroupMaskInverse.setIconSize(QtCore.QSize(24, 24))
        self.toolButtonGroupMaskInverse.setCheckable(True)
        self.toolButtonGroupMaskInverse.setObjectName("toolButtonGroupMaskInverse")
        self.horizontalLayout_50.addWidget(self.toolButtonGroupMaskInverse)
        self.verticalLayout_40.addLayout(self.horizontalLayout_50)
        self.scrollAreaClusters.setWidget(self.scrollAreaWidgetContentsClusters)
        self.verticalLayout_25.addWidget(self.scrollAreaClusters)
        self.horizontalLayout_51.addLayout(self.verticalLayout_25)
        self.tabWidgetMask.addTab(self.ClusterTab, icon27, "")
        self.horizontalLayout_26.addWidget(self.tabWidgetMask)
        pass
