# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/dhasterok/GitHub/LaserMapExplorer/designer/FileImportDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileImportDialog(object):
    def setupUi(self, FileImportDialog):
        FileImportDialog.setObjectName("FileImportDialog")
        FileImportDialog.resize(762, 496)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileImportDialog.sizePolicy().hasHeightForWidth())
        FileImportDialog.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(FileImportDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelDialog = QtWidgets.QLabel(FileImportDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        self.labelDialog.setFont(font)
        self.labelDialog.setObjectName("labelDialog")
        self.verticalLayout.addWidget(self.labelDialog)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelDirectory = QtWidgets.QLabel(FileImportDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDirectory.setFont(font)
        self.labelDirectory.setObjectName("labelDirectory")
        self.horizontalLayout.addWidget(self.labelDirectory)
        self.lineEditDirectory = QtWidgets.QLineEdit(FileImportDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEditDirectory.setFont(font)
        self.lineEditDirectory.setObjectName("lineEditDirectory")
        self.horizontalLayout.addWidget(self.lineEditDirectory)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(FileImportDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(FileImportDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(FileImportDialog)
        self.buttonBox.accepted.connect(FileImportDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(FileImportDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileImportDialog)

    def retranslateUi(self, FileImportDialog):
        _translate = QtCore.QCoreApplication.translate
        FileImportDialog.setWindowTitle(_translate("FileImportDialog", "Dialog"))
        self.labelDialog.setText(_translate("FileImportDialog", "Verify field import parameters"))
        self.labelDirectory.setText(_translate("FileImportDialog", "Directory:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("FileImportDialog", "Import?"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("FileImportDialog", "Filename"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("FileImportDialog", "Field Type"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("FileImportDialog", "Field"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("FileImportDialog", "Units"))
