# .github/workflows/pytest.yml
name: Run tests

on:
  push:
    branches:
      - test-github-actions
  pull_request:
    branches:
      - test-github-actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Install system dependencies
      run: |
        sudo apt-get update
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0 libxcb-shape0 libglib2.0-0 libgl1-mesa-dev
          sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        channels: conda-forge  # Add conda-forge channel

    - name: Install dependencies
      run: |
        conda create --name pyqt python=3.11 -y
        conda init bash
        source ~/.bashrc
        conda activate pyqt
        conda install -y pyqt pyqtgraph PyQtWebEngine pandas matplotlib scikit-learn scikit-learn-extra opencv openpyxl numexpr pytest pytest-qt pytest-mock
        conda install -y conda-forge/label/cf201901::scikit-fuzzy
        python -m pip install --upgrade pip
        pip install darkdetect cmcrameri rst2pdf
    - name: Run tests
      run: |
        source ~/.bashrc
        conda activate pyqt
        pytest

